##Spring Configuration
server:
  port: 8081
spring:
  application:
    name: balance
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:

urlBase: https://practicabanco.getsandbox.com:443

balance:
  url: /balances

transaction:
  url: /movements

transactionMoreMovement:
  url: /movements
